#!/usr/bin/env python3

import sys, os, time
import requests, json, configparser
from lcd_daemon import lcddriver

from lcd_daemon.daemon import LcdDaemon

if __name__ == "__main__":

    daemon = LcdDaemon()

    while True:
        tm = time.time()
        daemon.update()
        tm = time.time() - tm

        # To make the clock looks nicer, we try to
        # push updates once per second, so we
        # schedule the next call accordingly.
        time.sleep(max(0, 1 - tm))
